package com.example.dell.myapplication.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.dell.myapplication.db.DownListDb;
import com.example.dell.myapplication.db.userinfom;

import com.example.dell.myapplication.db.DownListDbDao;
import com.example.dell.myapplication.db.userinfomDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig downListDbDaoConfig;
    private final DaoConfig userinfomDaoConfig;

    private final DownListDbDao downListDbDao;
    private final userinfomDao userinfomDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        downListDbDaoConfig = daoConfigMap.get(DownListDbDao.class).clone();
        downListDbDaoConfig.initIdentityScope(type);

        userinfomDaoConfig = daoConfigMap.get(userinfomDao.class).clone();
        userinfomDaoConfig.initIdentityScope(type);

        downListDbDao = new DownListDbDao(downListDbDaoConfig, this);
        userinfomDao = new userinfomDao(userinfomDaoConfig, this);

        registerDao(DownListDb.class, downListDbDao);
        registerDao(userinfom.class, userinfomDao);
    }
    
    public void clear() {
        downListDbDaoConfig.clearIdentityScope();
        userinfomDaoConfig.clearIdentityScope();
    }

    public DownListDbDao getDownListDbDao() {
        return downListDbDao;
    }

    public userinfomDao getUserinfomDao() {
        return userinfomDao;
    }

}
